name: utilities
description: "utilities"
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  pinput: ^4.0.0
  dio: ^5.4.1
  get_storage: ^2.1.1
  lottie: ^2.7.0
  flutter_svg: ^2.0.0
  get: ^4.6.6
  go_router: ^13.2.0
  url_launcher: ^6.2.4
#  package_info_plus: ^5.0.1
  in_app_update: ^4.2.3
  cached_network_image: ^3.3.1
  razorpay_flutter: ^1.3.6
  # web view
  flutter_inappwebview: ^5.8.0

  validator_forge: ^1.0.0


  # firebase
#  firebase_messaging: ^14.7.10
#  firebase_in_app_messaging: ^0.7.3+5
#  firebase_core: ^3.3.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.0.0
  firebase_analytics: ^10.3.0
  firebase_crashlytics: ^3.2.0
  flutter_local_notifications: ^17.2.2
#  firebase_crashlytics: ^3.4.18
#  firebase_analytics: ^11.2.1


  flutter_html: ^3.0.0-beta.2

  http: ^1.2.0
  image_picker: ^1.0.8
  file_picker: ^8.0.0+1
  intl: ^0.19.0
  image_cropper: ^5.0.0

  study_abroad:
    path: /home/user/Apps/Gradding/gradding-packages/study_abroad

  package_info_plus: ^8.0.2
  device_info_plus: ^11.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  logger: ^2.1.0
  package_rename: ^1.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - assets/
     - assets/profile/
     - assets/banner/
     - assets/background/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
